ARG ELK_VERSION
FROM docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}

# Add your logstash plugins setup here
# Copy source files
#COPY logstash-input-rss2/ /usr/share/logstash-input-rss2/

# Install dependencies
#COPY *.sh /
#RUN /install-plugins.sh

#ENTRYPOINT ["/docker-entrypoint.sh"]

#CMD ["-f", "/etc/logstash/conf.d"]
